### ISSUE TITLE
Client Crash with the Sync mod in Multiplayer

### ISSUE THREAD

**Issue by Antinoe** [SanAndreaP/SanLib#5]
Using SanLib 1.6.3 with Sync 7.1.0 performs normally in Singleplayer. However, in a Multiplayer session, when a Client loads a chunk containing the Constructor Shell of another Player whose copy is inside of it, their game will crash. The one who injected their copy into the Constructor isn't affected.

I believe this is because their custom skin is loaded there, but SanLib and Sync are probably conflicting with such a concept. Since the Client can't render the custom skin set by the other user who used the Constructor, the game crashes.

**Comment by SanAndreaP** [comment]
Just cleaning up :)

The 1.12.2 version is not maintained anymore and the current iteration for 1.16 (unreleased, as of writing this) has this problem fixed.
